### DISCUSSION TITLE
Getting an error when working with mypy

### DISCUSSION THREAD

**Discussion by krausyd** [pydantic/pydantic#11973] [Question]
My mypy version is 1.x, my pydantic version is 2.x.

When creating a very basic model like:

```py
from pydantic import BaseModel

class MyClass(BaseModel):
    my_field: str
```

and using it in another project that has mypy enabled, I am getting the following error:

```
[CPython39-test]   File "xxxxxx/python3.9/site-packages/mypy/nodes.py", line 3581, in serialize
[CPython39-test]     assert not isinstance(
[CPython39-test] AssertionError: Definition of pydantic.types.JsonValue is unexpectedly incomplete
[CPython39-test] Errors were detected by mypy (exit code 1)
```

I have added the settings in the `.toml` file:
```toml
[tool.mypy]
plugins = ['pydantic.mypy']

[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true
```

in both projects, and having still the error. Has anyone faced this before?

#mypy #pydantic #jsonvalue #error
