### DISCUSSION TITLE
How to dynamically generate models?

### DISCUSSION THREAD

**Discussion by ssbarnea** [pydantic/pydantic#2407] [Question] [answered]
I need to generate a very long list of models programately and add them to the __root__ element of the of the TasksModel I am trying to build:

```python
class TasksFileModel(BaseModel):
    __root__: List[Union[TaskModel, BlockModel]]
   # this allows now two models previous defined, but I need to dynamically create and add ~5000 others
   # how can I do this?

    class Config:
        extra = Extra.forbid
        title = "Tasks Schema"
```

**Comment by PrettyWood** [comment, marked as answer]
Hmm not sure if this will be very efficient with so many models.
But for the dynamical approach maybe this can inspire you
```py
import string
from typing import Union

from pydantic import BaseModel, create_model, ValidationError

all_models = {
    c: create_model(f'Model{c}', **{c: (str, ...)})
    for c in string.ascii_lowercase
}


class M(BaseModel):
    __root__: Union[tuple(all_models.values())]

M.parse_obj({'a': 'foo'})
M.parse_obj({'b': 'foo'})
try:
    M.parse_obj({'aa': 'foo'})
except ValidationError as e:
    print(e)
```

**Reply by ssbarnea** [reply]
Thanks! I am going to give this a try and findout is is doable or not. If this does not work or proves to be too slow, I wonder if I could use some kind of regex matching that verifies that I only have one extra property which has a name that matches my regex.

To elaborate, assume model with several hardcoded properties and one extra one which needs to be a string among a my 5000 values, like below:

```yaml
name: anything
action1: ...
---
name: anything
action2: ...
---
name: anything
action1: ...
action2: ...
# ^ this one should fail because model should allow only one additional property that is part of my long list, not two.
```
