### DISCUSSION TITLE
How can I avoid deeply nested models when satisfying an externally defined schema?

### DISCUSSION THREAD

**Discussion by manterfield** [pydantic/pydantic#3426] [Question]
I'm not sure if this is currently possible so it might be a feature request (though I'm hoping I've just missed something obvious).

I'm creating models that map to some Kubernetes resources. One example target output is:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
  namespace: mynamespace
spec:
  entrypoint: hello
  templates:
  - name: hello
    dag:
      tasks:
      - name: greet
        inline:
          script:
            image: busybox
            command: [sh]
            source: |
              echo "Hello world!"
```

There's an obvious way to make this structure in Pydantic, but it requires lots of models that aren't actually meaningful from the perspective of the inputter.

Ideally the above would be represented as two models. One for the overall `Workflow` resource, and another for the individual `tasks`.

As an example, right now I have:

```python
class Metadata(BaseModel):
    generate_name: str = Field(None, alias="generateName")
    namespace: str = "mynamespace"

class Workflow(BaseModel):
    metadata: Metadata
    ...
```

In reality I'd much prefer to be able to just have `Metadata` as a property on `Workflow` and be able to provide `generate_name` and `namespace` on creation of the `Workflow`.

There's quite a few fields like this, forcing a nested structure that doesn't add much value. The `dag` key is probably the worst offender as it contains a single key `tasks` and in my use case will never have any other keys.

Is there a way around this, where ideally I can take values at the top level model but have them internally represented as arbitrarily nested structures?

EDIT: A comment on [issue 717](https://github.com/samuelcolvin/pydantic/issues/717#issuecomment-518580079) by @samuelcolvin mentions something called `DSN` and links to a file, but the link is now broken in that it currently points to a blank line. It sounds like it may at some point have provided an interface similar to what I wanted but for a specific field type?
