### DISCUSSION TITLE
List of Settings using dotenv

### DISCUSSION THREAD

**Discussion by arthurzenika** [pydantic/pydantic#4635] [Question]
I'm trying to model a Settings that would include a list of Settings (let's call them Endpoints), here would be some pseudo code : 

```python
class Endpoint(BaseSettings):
    url: str
    username: str
    password: str

class Settings(BaseSettings):
    endpoints: List[Endpoint]
    
    class Config:
        env_file = '.env'
        env_nested_delimiter = '__'
```

The `.env` would look something like :  

```
endpoints__foo__url=http://example.org
endpoints__foo__username=test
endpoints__foo__password=test
endpoints__bar__url=http://otherexample.org
endpoints__bar__username=blah
endpoints__bar__password=blah
```

... but ideally one could be able to configure this without naming the endpoints. 

Inspiration could be taken from how this could be done in TOML : 

```toml
[[endpoints]]
url=http://example.org
username=test
password=test
[[endpoints]]
url=http://otherexample.org
username=blah
password=blah
```
source : https://toml.io/en/v1.0.0#array-of-tables

I would I use pydantic for such a use case ? I've read https://pydantic-docs.helpmanual.io/usage/settings/#parsing-environment-variable-values multiple times and tested a few things but couldn't find how to do this...
