### DISCUSSION TITLE
How to allow third-party types to support Fields constraints and custom JSON schemas for dumping?

### DISCUSSION THREAD

**Discussion by Scientificmagic** [pydantic/pydantic#7235] [Question]
I followed the steps to allow [validation on third-party datatypes](https://docs.pydantic.dev/2.2/usage/types/custom/#handling-third-party-types), and now have an annotation that validates types and converts `strings` into `np.datetime64` objects seamlessly.

My next step is to get [field constraints](https://docs.pydantic.dev/2.2/usage/fields/#numeric-constraints) functioning to do some meaningful validation, and allowing for `.model_json_schema()` to display the constraints. I can't seem to find any documentation to support this behavior. I took a look at `@field_validator`, but I'm pretty sure it `.model_json_schema()` does not return the validator.
```python
PydanticDateTime64 = Annotated[numpy.datetime64, _DateTime64PydanticAnnotation]

class Foo(BaseModel):
    integer: int = Field(1, ge=0, le=100)
    dt64: PydanticDateTime64 = Field(
        numpy.datetime64("2023-01-01T00:00:00.000"),
        ge=numpy.datetime64("2023-01-01"),
    )

print(Foo.model_json_schema())
```
Output is missing `minimum` for `dt64`
```
properties:
  dt64:
    title: Dt64
    type: numpy.datetime64
  integer:
    default: 1
    maximum: 100
    minimum: 0
    title: Integer
    type: integer
title: Foo
type: object
```
