### DISCUSSION TITLE
Is it possible set default value of nested field based on key of dict field?

### DISCUSSION THREAD

**Discussion by jancespivo** [pydantic/pydantic#8074] [Question]
Hi,

I have this structure:

```yaml
services:
   ingestor:
       url: 'https://www.example.com/blabla'

   processor:
       ...
```

I want to achieve when no url is provided for some service it is computed based on the name of the service.
For example for `processor` above I want to have `url = 'https://www.myservice.com/processor'`

```python
class ServiceConfig(pydantic.BaseModel):
    url: str = f'https://www.myservice.com/{service_name}'  # this obviously can't work

class StaticConfig(pydantic.BaseModel):
    services: dict[str, ServiceConfig] = {}
    ...
```

Thanks for all advices!
