### DISCUSSION TITLE
Return default values of submodel

### DISCUSSION THREAD

**Discussion by mguyard** [pydantic/pydantic#9297] [Pydantic V2]
Hello,

I don't find how i can retreive default value of a submodel in case of my parent model is empty.
In my project, i use Pydantic for parsing/validate a configuration.

My Configuration :
```
...
  config:
    common:
      position:
          # opened: 100 # Default : 100% 
          # closed: 0 # Default : 0%
          # min_ratio_change: 5 # Default : 5%
          # min_time_change: 10 # Default : 10 minutes
      temperature:
          outdoor_sensor: "sensor.outdoor_sensor_temperature"
          indoor_sensor: "sensor.smoke_sensor_palier_air_temperature"
...
```

In this situation, only the key position is set (all content of position is commented).

My code :
```

class PositionConfig(BaseModel):
    opened: int = Field(ge=0, le=100, default=100)
    closed: int = Field(ge=0, le=100, default=0)
    min_ratio_change: int = Field(ge=0, le=100, default=5)
    min_time_change: PositiveInt = Field(ge=1, default=10)

class CommonConfig(BaseModel):
    position: PositionConfig = PositionConfig()
    temperature: TemperatureConfig
    lux: LuxConfig | None = None
    manual: ManualConfig
    opening: OpeningConfig
    closing: ClosingConfig

```

I want when i'm in this situation (None in position), use all default values of PositionConfig.
After multiple research, i've add a default value for also position :
```
position: PositionConfig = PositionConfig()
```

But i've still this error :
> 2024-04-21 12:09:14.459952 ERROR CoversManager: 1 validation error for Config
> common.position
>   Input should be a valid dictionary or instance of PositionConfig [type=model_type, input_value=None, input_type=NoneType]
>     For further information visit https://errors.pydantic.dev/2.7/v/model_type

If i comment position key in my configuration, this works and all default values are used but i want to manage the case of users forget to comment the position key.

If someone can help me to understand my error, this will be very appreciated.
Thank you
