### DISCUSSION TITLE
What is the best way to implement nestested configs with Pydantic Settings?

### DISCUSSION THREAD

**Discussion by matt3o** [pydantic/pydantic#9386] [Question]
![image](https://github.com/pydantic/pydantic/assets/7548699/6eb9dc88-8b8b-48ce-8ed3-11987711e770)

Hey guys!
I am trying to move my current config code to Pydantic settings. However when trying it out I realized I have to create at least 3 submodels even for the small example above. This makes the code extremly complicated and does not really simplify the process since I now have ultra small data classes.
Is there any good way to solve this all within the Setttings class?

Current solution:
```
Settings:
    litellm: LiteLLMSettings
...
LiteLLMSettings:
    model_list: List[Model]
...
Model:
    model_name: str
    litellm_params: LiteLLMParams

LiteLLMParams:
    model: str
...
```

Preferred solution something like
```
Settings:
    litellm:
        model_list: List[Model]

Model:
    model_name: str
    litellm_params:
        model: ...
        api_key: ...
```

Thanks and have a great weekend,
Matthias
