### DISCUSSION TITLE
Pydantic and Pydantic Settings don't seem to provide library stubs for MyPy

### DISCUSSION THREAD

**Discussion by bmitc** [pydantic/pydantic#9446] [Feature Request]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

In the [Pydantic documentation for MyPy](https://docs.pydantic.dev/latest/integrations/mypy/), it is stated that:

> Pydantic works well with [mypy](http://mypy-lang.org/) right out of the box.

> However, Pydantic also ships with a mypy plugin that adds a number of important pydantic-specific features to mypy that improve its ability to type-check your code.

However, MyPy generates errors for a simple module,

```
error: Cannot find implementation or library stub for module named "pydantic"  [import-not-found]
note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
error: Cannot find implementation or library stub for module named "pydantic_settings"  [import-not-found]
error: Class cannot subclass "BaseModel" (has type "Any")  [misc]
error: Class cannot subclass "BaseModel" (has type "Any")  [misc]
error: Class cannot subclass "BaseSettings" (has type "Any")  [misc]
```

I've removed the line numbers because they don't match up anyway to the code example below since I removed documentation lines, but they don't matter anyway since MyPy doesn't typecheck any Pydantic piece.

As a note, I am using Poetry. Here is my `pyproject.toml` configuration for MyPy:

```
[tool.mypy]
plugins = ["pydantic.mypy"]
strict = true
follow_imports = "silent"
```

Whether plugins is present or not makes no difference to the errors above.

### Example Code

```Python
from typing import Tuple, Type, Set
from pydantic import BaseModel
from pydantic_settings import (
    BaseSettings,
    PydanticBaseSettingsSource,
    SettingsConfigDict,
    YamlConfigSettingsSource,
)

class _DeviceConfig(BaseModel):
    bench: int
    side: Side

class _TCPDeviceConfig(BaseModel):
    ip_address: str
    port: int
    is_enabled: bool

class EmbeddedDeviceConfig(_TCPDeviceConfig, _DeviceConfig): pass

class FrontendDeviceConfig(_TCPDeviceConfig): pass

class TelemetryInfluxDBConfig(_TCPDeviceConfig): pass

class TelemetryGrafanaDBConfig(_TCPDeviceConfig): pass

class Settings(BaseSettings):
    telemetry_influxdb: TelemetryInfluxDBConfig
    telemetry_grafana: TelemetryGrafanaDBConfig
    embedded_devices: Set[EmbeddedDeviceConfig]
    frontend_device: FrontendDeviceConfig

    model_config = SettingsConfigDict(yaml_file="configuration.yaml")

    # pylint: disable=too-many-arguments
    @classmethod
    def settings_customise_sources(
        cls,
        settings_cls: Type[BaseSettings],
        init_settings: PydanticBaseSettingsSource,
        env_settings: PydanticBaseSettingsSource,
        dotenv_settings: PydanticBaseSettingsSource,
        file_secret_settings: PydanticBaseSettingsSource,
    ) -> Tuple[PydanticBaseSettingsSource, ...]:
        return (YamlConfigSettingsSource(settings_cls),)
```

### Python, Pydantic & OS Version

```Text
             pydantic version: 2.7.1
        pydantic-core version: 2.18.2
          pydantic-core build: profile=release pgo=true
                 install path: <poetry-project-root>\.venv\Lib\site-packages\pydantic
               python version: 3.12.1 (tags/v3.12.1:2305ca5, Dec  7 2023, 22:03:25) [MSC v.1937 64 bit (AMD64)]
                     platform: Windows-11-10.0.22631-SP0
             related packages: mypy-1.9.0 pydantic-settings-2.2.1 typing_extensions-4.11.0
                       commit: unknown
```

**Comment by Viicos** [comment]
There's probably an issue with your venv management: are you sure you are running `mypy` in the same env you have `pydantic` and `pydantic-settings` installed?

**Comment by bmitc** [comment]
I don't install anything with `pip` directly and always add dependencies via `poetry add <package>`. So for this case, I would have done `poetry add pydantic-settings`. Also, I force Poetry to write the `.venv` to the local project directory so that it's always using the local `.venv` and not some `.venv` somewhere else on the computer. Lastly, I always run MyPy via Poetry, so it's something like `poetry run mypy ...`. I have several dependencies installed, but Pydantic seems to be the only one with this issue.

Is there a listing of files that one would expect in the `.venv` for Pydantic such that MyPy can work with it?

**Comment by sydney-runkle** [comment]
Hmm, I'm going to move this to a discussion. I think @Viicos is right, this probably relates to venv management.

**Reply by bmitc** [reply]
How do you know that without any diagnosis or debugging steps? It seems like an assumption because, as I said, the several other packages I am using do not have this problem. So there's a virtual environment problem that only affects Pydantic? Maybe there is, but I need some help knowing what debugging steps the Pydantic team suggests.

**Reply by Viicos** [reply]
I've tried the following:

```sh
mkdir tmp && cd tmp/
poetry init
...
```

Ending up with the following `pyproject.toml`:

```toml
[tool.poetry]
name = "tmp"
version = "0.1.0"
description = ""
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pydantic = "^2.7.2"
pydantic-settings = "^2.2.1"
mypy = "^1.10.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
plugins = ["pydantic.mypy"]
strict = true
follow_imports = "silent"
```

Then:

```bash
poetry config virtualenvs.in-project true --local
mkdir tmp/
touch tmp/__init__.py  // and added your example file
poetry run mypy tmp/
// No errors
```

**Comment by lwaekfjlk** [comment]
I am facing the same issue.

**Comment by utopianf** [comment]
Same as me. I am working in python 3.11.8-slim docker, with Poetry and Pydantic version is following:
```
pydantic-settings = "^2.2.1"
pydantic = "^2.7.0"
mypy = "^1.8.0"
```

**Reply by utopianf** [reply]
This was due to my failure settings on pre-commit. I have to add `pydantic-settings` into the dependancy of mypy

**Reply by Insighttful** [reply]
Based on @utopianf comments, I noticed that `.pre-commit-config.yaml` should include include `pydantic` and `pydantic-settings` as additional dependencies for the mypy hook. 

After adding the following, pre-commit ran mypy without error:
```yaml
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.0
    hooks:
    - id: mypy
      args: ['--no-strict-optional', '--ignore-missing-imports', '--verbose']
      exclude: '/modules/database/prisma/.*|^prisma/.*|^\.venv\./'
      additional_dependencies:
        - pydantic
        - pydantic-settings
```

**Reply by ruwbine** [reply]
It helped for me, thanks!

**Comment by HoangNguyen689** [comment]
I also got this error.
Try it with pdm and everything is OK (even without plugin set up)
I guess there's something weird with poetry.

**Comment by michealroberts** [comment]
Yep so to fix this, in either your pyproject.toml:

```toml
[tool.mypy]
...
plugins = ["pydantic.mypy"]
```

or in your mypy.ini:

```ini
[mypy]
...
plugins = pydantic.mypy
```
