### ISSUE TITLE
mypy doesn't work with field type AnyHttpUrl

### ISSUE THREAD

**Issue by decastromonteiro** [pydantic/pydantic#3143]
### Checks

* [X] I added a descriptive title to this issue
* [X] I have searched (google, github) for similar issues and couldn't find anything
* [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.8.2
            pydantic compiled: True
                 install path: /home/***/.cache/pypoetry/virtualenvs/caishen-user-api-3c-BCzZJ-py3.9/lib/python3.9/site-packages/pydantic
               python version: 3.9.6 (default, Aug  8 2021, 10:09:11)  [GCC 9.3.0]
                     platform: Linux-4.19.128-microsoft-standard-x86_64-with-glibc2.31
     optional deps. installed: ['dotenv', 'email-validator', 'typing-extensions']
```

```py
from pydantic import AnyHttpUrl, BaseSettings

class Settings(BaseSettings):
    CORS_ORIGINS: List[AnyHttpUrl] = ["http://www.example.com"]
...
```
While running pre-commit with mypy, I get the following error:

```py
api/settings.py:44: error: List item 0 has incompatible type "str"; expected "AnyHttpUrl"
```

Just for reference, I'm using mypy 0.910 with the following config under pyproject.toml

```toml
[tool.mypy]
ignore_missing_imports = true
warn_unused_ignores = true
warn_redundant_casts = true
strict_optional = false
plugins = ["pydantic.mypy", "sqlalchemy.ext.mypy.plugin"]
disallow_untyped_defs = true
follow_imports = "silent"
```
I've also tried using `mypy.ini`, just to guarantee that it was not a parsing error from pyproject.toml, however the result is the same, so I think something is missing for this type validation on the mypy plugin.
