### ISSUE TITLE
Typing error using hierarchical custom `__init__`

### ISSUE THREAD

**Issue by marcelopgc** [pydantic/pydantic#5298]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

Using mypy v1.1.1, found a typing error using a hierarchical  custom `__init__` that constructs the object using positional arguments:
`Too many positional arguments for "MidleClass"  [misc]mypy(error)` (example below)

mypy version:
```bash
$ poetry show mypy
 name         : mypy                              
 version      : 1.1.1                             
 description  : Optional static typing for Python 

dependencies
 - mypy-extensions >=1.0.0
 - tomli >=1.1.0
 - typing-extensions >=3.10
 ```

pyproject.toml:
```toml
[tool.mypy]
strict = true
files = "src"
mypy_path = "src/"
namespace_packages = true
explicit_package_bases = true
follow_imports = "silent"
ignore_missing_imports = true
exclude = "(resources/.*)"
plugins = ["pydantic.mypy"]

[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true
warn_untyped_fields = true
```

### Example Code

```Python
from typing import Any

from pydantic import BaseModel


class BaseClass(BaseModel):
    a: str
    b: int

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        if len(args) == 2:
            kwargs = {"a": args[0], "b": args[1]}
        super().__init__(**kwargs)


class MidleClass(BaseClass):
    pass


x = BaseClass("a", 1)  # ok
y = MidleClass("a", 1)  # nok 'Too many positional arguments for "MidleClass"  [misc]mypy(error)'
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.7
            pydantic compiled: True
                 install path: /workspace/.venv/lib/python3.9/site-packages/pydantic
               python version: 3.9.16 (main, Jan 11 2023, 15:55:30)  [GCC 10.2.1 20210110]
                     platform: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.31
     optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [X] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.
