### ISSUE TITLE
Implement continuous profiling with `Codspeed`

### ISSUE THREAD

**Issue by sydney-runkle** [pydantic/pydantic#7961]
We should use `Codspeed` for continuous profiling of things we care about like import time, as we do on `pydantic-core`.

See https://github.com/pydantic/pydantic/pull/7947#issuecomment-1783231475 for some more context.

We'd love some help on this 🙏!

**Comment by lambertsbennett** [comment]
I would be into working on this!

**Comment by lambertsbennett** [comment]
OK so I think I have the basic setup as follows:
```yaml
name: codspeed

on:
  push:
    branches:
      - main
  pull_request:
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:

jobs:
  codspeed-profiling:
    name: codspeed profiling
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pdm-project/setup-pdm@v3
        with:
          python-version: '3.10'
          cache: true

      - name: install deps
        run: |
          pdm venv create --with-pip --force $PYTHON
          pdm install -G testing -G testing-extra -G email

      - name: Run CodSpeed benchmarks
        uses: CodSpeedHQ/action@v1
        with:
          run: pdm run pytest ./tests/benchmarks --codspeed
```
This runs, but then I get an error that it does not detect a repository or the token is invalid. I see on the codspeed website that normally in the with block you include a token like 
```yaml
token: ${{ secrets.CODSPEED_TOKEN }}
```
I don't have access to this token to test it fully, but otherwise the benchmarks run fine.
