### ISSUE TITLE
Mypy plugin gives false positive for `warn_required_dynamic_aliases` on properties & validators when `alias_generator` set

### ISSUE THREAD

**Issue by jwodder** [pydantic/pydantic#8008]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

If I (a) define a class that uses a class-wide `alias_generator`, (b) define a `@field_validator` classmethod or `@property` in that class, and (c) configure mypy to use the pydantic plugin with `warn_required_dynamic_aliases` set to true, then running mypy on the code will produce a false-positive error of "Required dynamic aliases disallowed  [pydantic-alias]" pointing to the last field validator or property in the class.

### Example Code

```Python
from pydantic import BaseModel, field_validator


def shishkebab(s: str) -> str:
    return s.replace("_", "-")


class Foo(BaseModel, alias_generator=shishkebab):
    some_field: str

    @field_validator("some_field")
    @classmethod
    def _strip(cls, value: str) -> str:
        return value.strip()


class Bar(BaseModel, alias_generator=shishkebab):
    an_attr: str

    @property
    def a_property(self) -> str:
        return self.an_attr * 2
```

mypy config from `pyproject.toml`:

```toml
[tool.mypy]
allow_incomplete_defs = false
allow_untyped_defs = false
ignore_missing_imports = false
no_implicit_optional = true
implicit_reexport = false
local_partial_types = true
pretty = true
show_error_codes = true
show_traceback = true
strict_equality = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
plugins = ["pydantic.mypy"]

[tool.pydantic-mypy]
init_forbid_extra = true
warn_required_dynamic_aliases = true
```

A complete MVCE repository can be found at <https://github.com/jwodder/pydantic-bug-20231103>.

### Python, Pydantic & OS Version

```Text
pydantic version: 2.4.2
        pydantic-core version: 2.10.1
          pydantic-core build: profile=release pgo=false
                 install path: /Users/jwodder/Library/Application Support/hatch/env/virtual/pydantic-bug-20231103/VwuLQ0A_/typing/lib/python3.11/site-packages/pydantic
               python version: 3.11.6 (main, Oct  2 2023, 13:45:54) [Clang 15.0.0 (clang-1500.0.40.1)]
                     platform: macOS-14.0-x86_64-i386-64bit
             related packages: mypy-1.6.1 typing_extensions-4.8.0
```
