### ISSUE TITLE
mypy arg-type error even with plugin config

### ISSUE THREAD

**Issue by dhruvinsh** [pydantic/pydantic#9689]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I am using recommended mypy config with project and I still get validation from mypy for arg-type
```
> mypy --config-file pyproject.toml test.py
test.py:9: error: Argument "a" to "Foo" has incompatible type "str"; expected "int"  [arg-type]
test.py:9: error: Argument "b" to "Foo" has incompatible type "str"; expected "int"  [arg-type]
Found 2 errors in 1 file (checked 1 source file)
```
Content of pyproject.toml
```toml
[tool.mypy]
plugins = ["pydantic.mypy"]

follow_imports = "silent"
warn_redundant_casts = true
warn_unused_ignores = true
disallow_any_generics = true
check_untyped_defs = true
no_implicit_reexport = true

# for strict mypy: (this is the tricky one :-))
disallow_untyped_defs = true

[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true

[tool.basedpyright]
typeCheckingMode = "off"

```

### Example Code

```Python
from pydantic import BaseModel


class Foo(BaseModel):
    a: int
    b: int


foo = Foo(a="1", b="2")
```

### Python, Pydantic & OS Version

```Text
> python -c "import pydantic.version; print(pydantic.version.version_info())"
             pydantic version: 2.7.4
        pydantic-core version: 2.18.4
          pydantic-core build: profile=release pgo=true
                 install path: /Users/ds/.local/share/virtualenvs/pydantic-I_zRehfl/lib/python3.11/site-packages/pydantic
               python version: 3.11.8 (main, Feb 25 2024, 17:34:51) [Clang 15.0.0 (clang-1500.1.0.2.5)]
                     platform: macOS-14.5-arm64-arm-64bit
             related packages: mypy-1.10.0 typing_extensions-4.12.2
                       commit: unknown
```
